### ISSUE TITLE
停止运行

### ISSUE THREAD

**Issue by 1mf2** [lizhangqu/chromium-net-for-android#7]
下载下来，编译打包的应用直接停止运行

05-12 14:04:48.347 28423 28423 I MainActivity: setup
05-12 14:04:48.352 28423 28423 W ChromiumLibraryLoader: libName:cronet.73.0.3653.0
05-12 14:04:48.357 28423 28423 W System.err: java.lang.ClassNotFoundException: Didn't find class "J.N" on path: DexPathList[[zip file "/data/app/io.github.lizhangqu.cronetsample-QTAA5gD4GmSB_aeozRJ4kQ==/base.apk"],nativeLibraryDirectories=[/data/app/io.github.lizhangqu.cronetsample-QTAA5gD4GmSB_aeozRJ4kQ==/lib/arm, /data/app/io.github.lizhangqu.cronetsample-QTAA5gD4GmSB_aeozRJ4kQ==/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
05-12 14:04:48.358 28423 28423 W System.err: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
05-12 14:04:48.358 28423 28423 W System.err: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
05-12 14:04:48.358 28423 28423 W System.err: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
05-12 14:04:48.358 28423 28423 W System.err: 	at java.lang.Runtime.nativeLoad(Native Method)
05-12 14:04:48.358 28423 28423 W System.err: 	at java.lang.Runtime.doLoad(Runtime.java:1099)
05-12 14:04:48.358 28423 28423 W System.err: 	at java.lang.Runtime.loadLibrary0(Runtime.java:1014)
05-12 14:04:48.358 28423 28423 W System.err: 	at java.lang.System.loadLibrary(System.java:1657)
05-12 14:04:48.358 28423 28423 W System.err: 	at io.github.lizhangqu.cronetsample.ChromiumLibraryLoader.loadLibrary(ChromiumLibraryLoader.java:56)
05-12 14:04:48.358 28423 28423 W System.err: 	at org.chromium.net.impl.VersionSafeCallbacks$LibraryLoader.loadLibrary(VersionSafeCallbacks.java:288)
05-12 14:04:48.359 28423 28423 W System.err: 	at org.chromium.net.impl.CronetLibraryLoader.ensureInitialized(CronetLibraryLoader.java:67)
05-12 14:04:48.359 28423 28423 W System.err: 	at org.chromium.net.impl.CronetUrlRequestContext.<init>(CronetUrlRequestContext.java:156)
05-12 14:04:48.359 28423 28423 W System.err: 	at org.chromium.net.impl.NativeCronetEngineBuilderImpl.build(NativeCronetEngineBuilderImpl.java:32)
05-12 14:04:48.359 28423 28423 W System.err: 	at org.chromium.net.CronetEngine$Builder.build(CronetEngine.java:319)
05-12 14:04:48.359 28423 28423 W System.err: 	at io.github.lizhangqu.cronetsample.MainActivity.ensureCornetEngine(MainActivity.java:253)
05-12 14:04:48.359 28423 28423 W System.err: 	at io.github.lizhangqu.cronetsample.MainActivity.onCreate(MainActivity.java:133)
05-12 14:04:48.359 28423 28423 W System.err: 	at android.app.Activity.performCreate(Activity.java:7259)
05-12 14:04:48.359 28423 28423 W System.err: 	at android.app.Activity.performCreate(Activity.java:7250)
05-12 14:04:48.359 28423 28423 W System.err: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1215)
05-12 14:04:48.360 28423 28423 W System.err: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2751)
05-12 14:04:48.360 28423 28423 W System.err: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2876)
05-12 14:04:48.360 28423 28423 W System.err: 	at android.app.ActivityThread.-wrap11(Unknown Source:0)
05-12 14:04:48.360 28423 28423 W System.err: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1609)
05-12 14:04:48.360 28423 28423 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:106)
05-12 14:04:48.360 28423 28423 W System.err: 	at android.os.Looper.loop(Looper.java:164)
05-12 14:04:48.360 28423 28423 W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:6606)
05-12 14:04:48.360 28423 28423 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
05-12 14:04:48.360 28423 28423 W System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
05-12 14:04:48.360  1520  1531 D PackageManager:  isRuntimePermission = false

05-12 14:04:48.420 28476 28476 F DEBUG   : Revision: '0'
05-12 14:04:48.420 28476 28476 F DEBUG   : ABI: 'arm'
05-12 14:04:48.420 28476 28476 F DEBUG   : pid: 28423, tid: 28423, name: qu.cronetsample  >>> io.github.lizhangqu.cronetsample <<<
05-12 14:04:48.420 28476 28476 F DEBUG   : signal 5 (SIGTRAP), code 1 (TRAP_BRKPT), fault addr 0xc9fa56ba
05-12 14:04:48.420 28476 28476 F DEBUG   :     r0 00000000  r1 e96bc3c0  r2 00000400  r3 00000000
05-12 14:04:48.420 28476 28476 F DEBUG   :     r4 ffbf1738  r5 ffbf173c  r6 ea376788  r7 ffbf12f8
05-12 14:04:48.420 28476 28476 F DEBUG   :     r8 00000047  r9 ffbf12dd  sl ffbf12dc  fp ea37b1b8
05-12 14:04:48.420 28476 28476 F DEBUG   :     ip ffbf12fc  sp ffbf12c8  lr c9f95ab7  pc c9f95bb0  cpsr 60010030
05-12 14:04:48.536 28476 28476 F DEBUG   : 
05-12 14:04:48.536 28476 28476 F DEBUG   : backtrace:
05-12 14:04:48.536 28476 28476 F DEBUG   :     #00 pc 0010dbb0  /data/app/io.github.lizhangqu.cronetsample-QTAA5gD4GmSB_aeozRJ4kQ==/lib/arm/libcronet.73.0.3653.0.so (offset 0xbf000)
05-12 14:04:48.536 28476 28476 F DEBUG   :     #01 pc 00145b4b  /data/app/io.github.lizhangqu.cronetsample-QTAA5gD4GmSB_aeozRJ4kQ==/lib/arm/libcronet.73.0.3653.0.so (offset 0xbf000)
05-12 14:04:48.536 28476 28476 F DEBUG   :     #02 pc 000e8095  /data/app/io.github.lizhangqu.cronetsample-QTAA5gD4GmSB_aeozRJ4kQ==/lib/arm/libcronet.73.0.3653.0.so (offset 0xbf000)
05-12 14:04:48.537 28476 28476 F DEBUG   :     #03 pc 0024f1b1  /system/lib/libart.so (art::JavaVMExt::LoadNativeLibrary(_JNIEnv*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, _jobject*, _jstring*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>*)+1884)
05-12 14:04:48.537 28476 28476 F DEBUG   :     #04 pc 0000315f  /system/lib/libopenjdkjvm.so (JVM_NativeLoad+194)
05-12 14:04:48.537 28476 28476 F DEBUG   :     #05 pc 00254621  /system/framework/arm/boot-core-oj.oat (offset 0x1cb000) (java.lang.Runtime.nativeLoad+160)
05-12 14:04:48.537 28476 28476 F DEBUG   :     #06 pc 00400f75  /system/lib/libart.so (art_quick_invoke_stub_internal+68)
05-12 14:04:48.537 28476 28476 F DEBUG   :     #07 pc 004061eb  /system/lib/libart.so (art_quick_invoke_static_stub+226)

**Comment by carsonyu** [comment]
先是遇到 unused DT entry 的问题，clean elf 解决后又碰到这个J.N的问题，还没找到解决思路。。。

**Comment by carsonyu** [comment]
> 先是遇到 unused DT entry 的问题，clean elf 解决后又碰到这个J.N的问题，还没找到解决思路。。。

破案了，是没引入jar包
